version: '3'
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    volumes:
      - .:/var/www/html
      - ~/.aws:/root/.aws
    working_dir: /var/www/html
    entrypoint: ash
    tty: true

